// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxH-77d47S5FgR7EPuWN5ftdqKwDZl1IQ',
    appId: '1:948578827288:web:2ea49ebae915dc8ef9576d',
    messagingSenderId: '948578827288',
    projectId: 'filmify-aac45',
    authDomain: 'filmify-aac45.firebaseapp.com',
    storageBucket: 'filmify-aac45.firebasestorage.app',
    measurementId: 'G-F9L3MZ5MED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1BZlAoeu-IZGZpK21K2GAxbo9TSl025E',
    appId: '1:948578827288:android:0c7102e84632ea0ff9576d',
    messagingSenderId: '948578827288',
    projectId: 'filmify-aac45',
    storageBucket: 'filmify-aac45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6jygQeq2hiqiSlx0jWNy4YE-hRHa0Jg',
    appId: '1:948578827288:ios:455acddfa3b5676ff9576d',
    messagingSenderId: '948578827288',
    projectId: 'filmify-aac45',
    storageBucket: 'filmify-aac45.firebasestorage.app',
    iosBundleId: 'com.example.filmify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI6jygQeq2hiqiSlx0jWNy4YE-hRHa0Jg',
    appId: '1:948578827288:ios:455acddfa3b5676ff9576d',
    messagingSenderId: '948578827288',
    projectId: 'filmify-aac45',
    storageBucket: 'filmify-aac45.firebasestorage.app',
    iosBundleId: 'com.example.filmify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxH-77d47S5FgR7EPuWN5ftdqKwDZl1IQ',
    appId: '1:948578827288:web:ce20f3daca03bf77f9576d',
    messagingSenderId: '948578827288',
    projectId: 'filmify-aac45',
    authDomain: 'filmify-aac45.firebaseapp.com',
    storageBucket: 'filmify-aac45.firebasestorage.app',
    measurementId: 'G-2914TZSV85',
  );
}
